apiVersion: {{ include "networkpolicyversion" . }}
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Egress from pods labeled with 'networking.gardener.cloud/to-metadata=allowed'
      to CloudProvider's specific metadata service IP.
  name: allow-to-metadata
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-metadata: allowed
{{- if .Values.metadataService }}
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.metadataService }}
{{- else }}
  egress: []
{{- end }}
  policyTypes:
  - Egress
  ingress: []
