images:
  grafana: image-repository:image-tag
  busybox: image-repository:image-tag

ingress:
  class: nginx
  hosts:
  - hostName: g.seed-1.example.com
    secretName: grafana-tls
  # admin : admin base64 encoded
  basicAuthSecret: YWRtaW46JGFwcjEkSWRSaVM5c3MkR3U1MHMxaGUwL2Z6Tzh2elE4S1BEMQ==
replicas: 1
ports:
  prometheus: 9090
  grafana: 3000

vpaEnabled: false
role: operators
extensions:
  dashboards: ""

sni:
  enabled: false

nodeLocalDNS:
  enabled: false
