# List of all container images which are deployed by the Gardener.
# In case an image can only be used for a specific Kubernetes version, the
# entry must have a key "runtimeVersion" whose value describe for which kubernetes runtime
# the respective tag can be used. The syntax must be as described in the
# Masterminds/semver package: https://github.com/Masterminds/semver#hyphen-range-comparisons.
images:
# Seed bootstrap
- name: pause-container
  sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
  repository: gcr.io/google_containers/pause-amd64
  tag: "3.1"

# Seed controlplane
- name: etcd
  sourceRepository: github.com/coreos/etcd
  repository: quay.io/coreos/etcd
  tag: v3.3.13
- name: hyperkube
  sourceRepository: github.com/kubernetes/kubernetes
  repository: k8s.gcr.io/hyperkube
- name: coreos-cloudinit
  sourceRepository: github.com/coreos/coreos-cloudinit
  repository: hisshadow85/coreos-cloudinit
  tag: "0.0.13"
- name: cluster-autoscaler
  sourceRepository: github.com/gardener/autoscaler
  repository: eu.gcr.io/gardener-project/gardener/autoscaler/cluster-autoscaler
  tag: "0.6.0"
- name: gardener-resource-manager
  sourceRepository: github.com/gardener/gardener-resource-manager
  repository: eu.gcr.io/gardener-project/gardener/gardener-resource-manager
  tag: "0.7.0"
- name: vpn-seed
  sourceRepository: github.com/gardener/vpn
  repository: eu.gcr.io/gardener-project/gardener/vpn-seed
  tag: "0.16.0"
- name: dependency-watchdog
  sourceRepository: github.com/gardener/dependency-watchdog
  repository: eu.gcr.io/gardener-project/gardener/dependency-watchdog
  tag: "0.2.0"

# Monitoring
- name: alertmanager
  sourceRepository: github.com/prometheus/alertmanager
  repository: quay.io/prometheus/alertmanager
  tag: v0.18.0
- name: prometheus
  sourceRepository: github.com/prometheus/prometheus
  repository: quay.io/prometheus/prometheus
  tag: v2.12.0
- name: configmap-reloader
  sourceRepository: github.com/jimmidyson/configmap-reload
  repository: quay.io/coreos/configmap-reload
  tag: v0.0.1
- name: kube-state-metrics
  sourceRepository: github.com/kubernetes/kube-state-metrics
  repository: quay.io/coreos/kube-state-metrics
  tag: v1.7.2
- name: node-exporter
  sourceRepository: github.com/prometheus/node_exporter
  repository: quay.io/prometheus/node-exporter
  tag: v0.18.1
- name: grafana
  sourceRepository: github.com/grafana/grafana
  repository: grafana/grafana
  tag: "6.3.2"
- name: blackbox-exporter
  sourceRepository: github.com/prometheus/blackbox_exporter
  repository: quay.io/prometheus/blackbox-exporter
  tag: v0.14.0
- name: metrics-server
  sourceRepository: github.com/kubernetes-incubator/metrics-server
  repository: k8s.gcr.io/metrics-server-amd64
  tag: v0.3.3
  targetVersion: ">= 1.11"
- name: metrics-server
  sourceRepository: github.com/kubernetes-incubator/metrics-server
  repository: k8s.gcr.io/metrics-server-amd64
  tag: v0.3.1
  targetVersion: 1.10.x

# Shoot core addons
- name: vpn-shoot
  sourceRepository: github.com/gardener/vpn
  repository: eu.gcr.io/gardener-project/gardener/vpn-shoot
  tag: "0.16.0"
- name: coredns
  sourceRepository: github.com/coredns/coredns
  repository: coredns/coredns
  tag: "1.6.3"
- name: node-problem-detector
  sourceRepository: github.com/kubernetes/node-problem-detector
  repository: k8s.gcr.io/node-problem-detector
  tag: "v0.7.1"

# Shoot optional addons
- name: kubernetes-dashboard
  sourceRepository: github.com/kubernetes/dashboard
  repository: k8s.gcr.io/kubernetes-dashboard-amd64
  tag: v1.10.1
- name: nginx-ingress-controller
  sourceRepository: github.com/kubernetes/ingress-nginx
  repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
  tag: "0.22.0"
- name: ingress-default-backend
  sourceRepository: github.com/gardener/ingress-default-backend
  repository: eu.gcr.io/gardener-project/gardener/ingress-default-backend
  tag: "0.7.0"

# Miscellaenous
- name: busybox
  sourceRepository: github.com/mirror/busybox
  repository: busybox
  tag: "1.29.2"
- name: alpine
  repository: alpine
  tag: "3.8"
- name: alpine-iptables
  repository: eu.gcr.io/gardener-project/alpine-iptables
  tag: "3.9"

# Logging
- name: fluentd-es
  sourceRepository: github.com/gardener/logging
  repository: eu.gcr.io/gardener-project/gardener/fluentd-es
  tag: "0.19.0"
- name: fluent-bit
  sourceRepository: github.com/fluent/fluent-bit
  repository: fluent/fluent-bit
  tag: "1.0.6"
- name: elasticsearch-oss
  sourceRepository: github.com/elastic/elasticsearch-docker
  repository: docker.elastic.co/elasticsearch/elasticsearch-oss
  tag: "6.7.1"
- name: elasticsearch-metrics-exporter
  sourceRepository: github.com/justwatchcom/elasticsearch_exporter
  repository: justwatch/elasticsearch_exporter
  tag: "1.0.2"
- name: elasticsearch-searchguard-oss
  sourceRepository: github.com/floragunncom/search-guard
  repository: floragunncom/sg-elasticsearch
  tag: "6.7.1-oss-25.0"
- name: curator-es
  sourceRepository: github.com/gardener/logging
  repository: eu.gcr.io/gardener-project/gardener/curator-es
  tag: "0.19.0"
- name: kibana-oss
  sourceRepository: github.com/elastic/kibana-docker
  repository: docker.elastic.co/kibana/kibana-oss
  tag: "6.7.1"
- name: sg-sgadmin
  sourceRepository: github.com/floragunncom/search-guard
  repository: floragunncom/sg-sgadmin
  tag: "6.7.1-25.0"

# VPA
- name: vpa-admission-controller
  sourceRepository: github.com/kubernetes/autoscaler
  repository: k8s.gcr.io/vpa-admission-controller
  tag: "0.6.3"
- name: vpa-recommender
  sourceRepository: github.com/kubernetes/autoscaler
  repository: k8s.gcr.io/vpa-recommender
  tag: "0.6.3"
- name: vpa-updater
  sourceRepository: github.com/kubernetes/autoscaler
  repository: k8s.gcr.io/vpa-updater
  tag: "0.6.3"
- name: vpa-exporter
  sourceRepository: github.com/gardener/vpa-exporter
  repository: eu.gcr.io/gardener-project/gardener/vpa-exporter
  tag: "0.1.5"

# HVPA
- name: hvpa-controller
  sourceRepository: github.com/gardener/hvpa-controller
  repository: eu.gcr.io/gardener-project/gardener/hvpa-controller
  tag: "0.1.0"
