# List of all container images which are deployed by the Gardener.
# In case an image can only be used for a specific Kubernetes version, the
# entry must have a key "runtimeVersion" whose value describe for which kubernetes runtime
# the respective tag can be used. The syntax must be as described in the
# Masterminds/semver package: https://github.com/Masterminds/semver#hyphen-range-comparisons.
images:
# Gardener components
- name: gardenlet
  sourceRepository: github.com/gardener/gardener
  repository: eu.gcr.io/gardener-project/gardener/gardenlet
- name: gardener-seed-admission-controller
  sourceRepository: github.com/gardener/gardener
  repository: eu.gcr.io/gardener-project/gardener/seed-admission-controller

# Seed bootstrap
- name: pause-container
  sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
  repository: gcr.io/google_containers/pause-amd64
  tag: "3.1"
- name: etcd-druid
  sourceRepository: github.com/gardener/etcd-druid
  repository: eu.gcr.io/gardener-project/gardener/etcd-druid
  tag: "v0.3.0"
- name: gardener-resource-manager
  sourceRepository: github.com/gardener/gardener-resource-manager
  repository: eu.gcr.io/gardener-project/gardener/gardener-resource-manager
  tag: "v0.12.0"
- name: dependency-watchdog
  sourceRepository: github.com/gardener/dependency-watchdog
  repository: eu.gcr.io/gardener-project/gardener/dependency-watchdog
  tag: "0.4.0"

# Seed controlplane
- name: hyperkube # used for kubectl + kubelet binaries on the worker nodes
  sourceRepository: github.com/kubernetes/kubernetes
  repository: k8s.gcr.io/hyperkube
- name: kube-apiserver
  sourceRepository: github.com/kubernetes/kubernetes
  repository: k8s.gcr.io/hyperkube
  targetVersion: "< 1.17"
- name: kube-apiserver
  sourceRepository: github.com/kubernetes/kubernetes
  repository: k8s.gcr.io/kube-apiserver
  targetVersion: ">= 1.17"
- name: kube-controller-manager
  sourceRepository: github.com/kubernetes/kubernetes
  repository: k8s.gcr.io/hyperkube
  targetVersion: "< 1.17"
- name: kube-controller-manager
  sourceRepository: github.com/kubernetes/kubernetes
  repository: k8s.gcr.io/kube-controller-manager
  targetVersion: ">= 1.17"
- name: kube-scheduler
  sourceRepository: github.com/kubernetes/kubernetes
  repository: k8s.gcr.io/hyperkube
  targetVersion: "< 1.17"
- name: kube-scheduler
  sourceRepository: github.com/kubernetes/kubernetes
  repository: k8s.gcr.io/kube-scheduler
  targetVersion: ">= 1.17"
- name: kube-proxy
  sourceRepository: github.com/kubernetes/kubernetes
  repository: k8s.gcr.io/hyperkube
  targetVersion: "< 1.17"
- name: kube-proxy
  sourceRepository: github.com/kubernetes/kubernetes
  repository: k8s.gcr.io/kube-proxy
  targetVersion: ">= 1.17"
- name: cluster-autoscaler
  sourceRepository: github.com/gardener/autoscaler
  repository: eu.gcr.io/gardener-project/gardener/autoscaler/cluster-autoscaler
  tag: "0.9.0"
- name: vpn-seed
  sourceRepository: github.com/gardener/vpn
  repository: eu.gcr.io/gardener-project/gardener/vpn-seed
  tag: "0.19.0"

# Monitoring
- name: alertmanager
  sourceRepository: github.com/prometheus/alertmanager
  repository: quay.io/prometheus/alertmanager
  tag: v0.18.0
- name: prometheus
  sourceRepository: github.com/prometheus/prometheus
  repository: quay.io/prometheus/prometheus
  tag: v2.12.0
- name: configmap-reloader
  sourceRepository: github.com/jimmidyson/configmap-reload
  repository: quay.io/coreos/configmap-reload
  tag: v0.0.1
- name: kube-state-metrics
  sourceRepository: github.com/kubernetes/kube-state-metrics
  repository: quay.io/coreos/kube-state-metrics
  tag: v1.9.3
- name: node-exporter
  sourceRepository: github.com/prometheus/node_exporter
  repository: quay.io/prometheus/node-exporter
  tag: v0.18.1
- name: grafana
  sourceRepository: github.com/grafana/grafana
  repository: grafana/grafana
  tag: "7.0.1"
- name: blackbox-exporter
  sourceRepository: github.com/prometheus/blackbox_exporter
  repository: quay.io/prometheus/blackbox-exporter
  tag: v0.14.0
- name: metrics-server
  sourceRepository: github.com/kubernetes-incubator/metrics-server
  repository: k8s.gcr.io/metrics-server-amd64
  tag: v0.3.6
  targetVersion: ">= 1.11"
- name: metrics-server
  sourceRepository: github.com/kubernetes-incubator/metrics-server
  repository: k8s.gcr.io/metrics-server-amd64
  tag: v0.3.1
  targetVersion: 1.10.x

# Shoot core addons
- name: vpn-shoot
  sourceRepository: github.com/gardener/vpn
  repository: eu.gcr.io/gardener-project/gardener/vpn-shoot
  tag: "0.19.0"
- name: coredns
  sourceRepository: github.com/coredns/coredns
  repository: coredns/coredns
  tag: "1.6.3"
- name: node-problem-detector
  sourceRepository: github.com/kubernetes/node-problem-detector
  repository: k8s.gcr.io/node-problem-detector
  tag: "v0.7.1"

# Shoot optional addons
- name: kubernetes-dashboard
  sourceRepository: github.com/kubernetes/dashboard
  repository: k8s.gcr.io/kubernetes-dashboard-amd64
  tag: v1.10.1
  targetVersion: "< 1.16"
- name: kubernetes-dashboard
  sourceRepository: github.com/kubernetes/dashboard
  repository: kubernetesui/dashboard
  tag: v2.0.0
  targetVersion: ">= 1.16"
- name: kubernetes-dashboard-metrics-scraper
  sourceRepository: github.com/kubernetes/dashboard
  repository: kubernetesui/metrics-scraper
  tag: v1.0.4
  targetVersion: ">= 1.16"
- name: nginx-ingress-controller
  sourceRepository: github.com/kubernetes/ingress-nginx
  repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
  tag: "0.22.0"
- name: ingress-default-backend
  sourceRepository: github.com/gardener/ingress-default-backend
  repository: eu.gcr.io/gardener-project/gardener/ingress-default-backend
  tag: "0.8.0"

# Miscellaenous
- name: busybox
  sourceRepository: github.com/mirror/busybox
  repository: busybox
  tag: "1.29.2"
- name: alpine
  repository: alpine
  tag: "3.10.3"
- name: alpine-iptables
  sourceRepository: github.com/DockToFuture/alpine-iptables
  repository: eu.gcr.io/gardener-project/alpine-iptables
  tag: "3.10.3"

# Logging
- name: fluent-bit
  sourceRepository: github.com/fluent/fluent-bit
  repository: hisshadow85/fluent-bit-to-loki
  tag: "0.1.1"
- name: loki
  sourceRepository: github.com/grafana/loki
  repository: grafana/loki
  tag: "1.5.0"



# VPA
- name: vpa-admission-controller
  sourceRepository: github.com/kubernetes/autoscaler
  repository: k8s.gcr.io/vpa-admission-controller
  tag: "0.6.3"
- name: vpa-recommender
  sourceRepository: github.com/kubernetes/autoscaler
  repository: k8s.gcr.io/vpa-recommender
  tag: "0.6.3"
- name: vpa-updater
  sourceRepository: github.com/kubernetes/autoscaler
  repository: k8s.gcr.io/vpa-updater
  tag: "0.6.3"
- name: vpa-exporter
  sourceRepository: github.com/gardener/vpa-exporter
  repository: eu.gcr.io/gardener-project/gardener/vpa-exporter
  tag: "0.1.5"

# HVPA
- name: hvpa-controller
  sourceRepository: github.com/gardener/hvpa-controller
  repository: eu.gcr.io/gardener-project/gardener/hvpa-controller
  tag: "v0.2.5"
