apiVersion: {{ include "networkpolicyversion" . }}
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Ingress and Egress between etcd-{{ .Values.role }} peers.
  name: allow-etcd-{{ .Values.role }}-peering
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: etcd-statefulset
      garden.sapcloud.io/role: controlplane
      role: {{ .Values.role }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: etcd-statefulset
          garden.sapcloud.io/role: controlplane
          role: {{ .Values.role }}
    ports:
    - protocol: TCP
      port: {{ .Values.servicePorts.server }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: etcd-statefulset
          garden.sapcloud.io/role: controlplane
          role: {{ .Values.role }}
    ports:
    - protocol: TCP
      port: {{ .Values.servicePorts.server }}
  policyTypes:
  - Egress
  - Ingress
