---
apiVersion: {{ include "rbacversion" . }}
kind: Role
metadata:
  name: cloud-config-downloader
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
  resourceNames:
{{- range $key, $value := .Values.workers }}
  - {{ $value.secretName }}
{{- end }}
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create