{{- range $key, $value := .Values.workers }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $value.secretName }}
  namespace: kube-system
data:
  cloud_config: {{ $value.cloudConfig | b64enc }}
{{- end }}
