---
apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: grafana-{{ .Values.role }}
  namespace: {{ .Release.Namespace }}
  labels:
    garden.sapcloud.io/role: monitoring
    component: grafana
    role: {{ .Values.role }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      component: grafana
      role: {{ .Values.role }}
  template:
    metadata:
      annotations:
        checksum/configmap-dashboards: {{ include (print $.Template.BasePath "/grafana-dashboards-configmap.yaml") . | sha256sum }}
        checksum/configmap-datasources: {{ include (print $.Template.BasePath "/grafana-datasources-configmap.yaml") . | sha256sum }}
        checksum/configmap-dashboard-providers: {{ include (print $.Template.BasePath "/grafana-dashboard-providers-configmap.yaml") . | sha256sum }}
      labels:
        garden.sapcloud.io/role: monitoring
        component: grafana
        networking.gardener.cloud/to-dns: allowed
        role: {{ .Values.role }}
        networking.gardener.cloud/to-loki: allowed
    spec:
      initContainers:
      - name: init-prometheus
        image: {{ index .Values.images "busybox" }}
        command: ['sh', '-c', 'until wget -T 5 -qO- http://prometheus-web/-/healthy > /dev/null; do echo waiting for Prometheus; sleep 2; done;']
      containers:
      - name: grafana
        image: {{ index .Values.images "grafana" }}
        imagePullPolicy: IfNotPresent
        env:
{{- if eq .Values.role "operators" }}
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "false"
{{- else }}
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "true"
{{- end }}
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_SNAPSHOTS_EXTERNAL_ENABLED
          value: "false"
        - name: GF_ALERTING_ENABLED
          value: "false"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/grafana-storage
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboard-providers
          mountPath: /etc/grafana/provisioning/dashboards
        ports:
        - name: web
          containerPort: {{ required ".ports.grafana is required" .Values.ports.grafana }}
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 128Mi
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: grafana-dashboards
        configMap:
          name: grafana-{{ .Values.role }}-dashboards
      - name: grafana-datasources
        configMap:
          name: grafana-{{ .Values.role }}-datasources
      - name: grafana-dashboard-providers
        configMap:
          name: grafana-{{ .Values.role }}-dashboard-providers
