apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-{{ .Values.role }}-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    component: grafana
    role: {{ .Values.role }}
data:
  datasources.yaml: |-
    # config file version
    apiVersion: 1

    # list of datasources that should be deleted from the database
    deleteDatasources:
    - name: Graphite
      orgId: 1

    # list of datasources to insert/update depending
    # whats available in the database
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-web:80
      basicAuth: false
      isDefault: true
      version: 1
      editable: false
    - name: loki
      type: loki
      access: proxy
      url: http://loki.{{ .Release.Namespace }}.svc:3100
      jsonData:
        maxLines: 1000
