{
 "title": "Kubernetes Pods",
 "tags": [
  "kubernetes",
  "seed",
  "shoot"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "type", "label": "Type", "query": "seed,shoot" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{type=~\"$type\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{type=~\"$type\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Limits:"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"$container\",pod=~\"$pod\"}[2m]))",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{container=~\"$container\",pod=~\"$pod\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{container=~\"$container\",pod=~\"$pod\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[2m])) by (pod)",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[2m])) by (pod)",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Pod File System Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{pod=~\"$pod\", container=~\"$container\",})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(container_fs_usage_bytes{pod=~\"$pod\", image!=\"\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Pod Logs",
   "type": "logs",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{pod_name=~\"$pod\", container_name=~\"$container\"}"
    }
   ]
  }
 ]
}