### !CAUTION! ###
# Most cloud providers have a limit of 16 KB regarding the user-data that may be sent during VM creation.
# The result of this operating system config is exactly the user-data that will be sent to the providers.
# We must not exceed the 16 KB, so be careful when extending/changing anything in here.
### !CAUTION! ###
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: OperatingSystemConfig
metadata:
  name: {{ required "secretName is required" .Values.secretName }}-downloader
  namespace: {{ .Release.Namespace }}
  annotations:
    gardener.cloud/operation: reconcile
spec:
  type: {{ required "type is required" .Values.type }}
  purpose: {{ required "purpose is required" .Values.purpose }}
  units:
  - name: cloud-config-downloader.service
    command: start
    enable: true
    content: |
      [Unit]
      Description=alabala
      After=docker.service docker.socket
      Wants=docker.socket
      [Install]
      WantedBy=multi-user.target
      [Service]
      #Restart=on-failure
      #RestartSec=30
      EnvironmentFile=/etc/environment
      ExecStartPre=/bin/docker run --rm -v /opt/bin:/opt/bin:rw {{ required "images.coreosCloudinit is required" (index .Values.images "coreos-cloudinit") }} cp /coreos-cloudinit /opt/bin/
      ExecStart=/opt/bin/coreos-cloudinit \
              --from-kube-api=/var/lib/cloud-config-downloader/credentials/kubeconfig \
              --kube-secret-name={{ required "secretName is required" .Values.secretName }}
  files:
  - path: /var/lib/kubelet/kubeconfig-bootstrap
    permissions: 0640
    content:
      inline:
        data: {{ include "bootstrap-kubeconfig" . | b64enc }}
  - path: /var/lib/cloud-config-downloader/credentials/ca.crt
    permissions: 0644
    content:
      secretRef:
        name: cloud-config-downloader
        dataKey: ca.crt
  - path: /var/lib/cloud-config-downloader/credentials/kubeconfig
    permissions: 0640
    content:
      secretRef:
        name: cloud-config-downloader
        dataKey: kubeconfig
